<?php
$doc_root = $_SERVER['DOCUMENT_ROOT'];

//load all helper functions
foreach(glob("$doc_root/app/helpers/*.php") as $file)
	include_once $file;

$fields = array(
	"site_title",
	"site_description",
	"site_root",
	"pretty_urls",
	"host",
	"host_root",
	"theme",
	"smartypants",
	"page_order"
);

$error = false;

if(sizeof($_POST) > 0) {
	foreach($fields as $field) {
		//not set or blank
		if(!isset($_POST[$field]) || !$_POST[$field]) {
			switch($field) {
				case "site_root":
					$config[$field] = trim_slashes(str_replace(basename(request_url()), "", request_url()));
					break;
				case "pretty_urls":
				case "smartypants":
					$config[$field] = 0;
					break;
				case "host_root":
					$config[$field] = "/";
					break;
				case "page_order":
					$config[$field] = "{}";
					break;
				default: 
					$config[$field] = "";
			}
		}
		//if set, sanitize
		else {
			switch($field) {
				case "site_root":
					$config[$field] = trim_slashes($_POST[$field]);
					break;
				case "host_root":
					$config[$field] = "/".trim_slashes($_POST[$field]);
					break;
				case "page_order":
					$config[$field] = json_decode(str_replace('\"', '"', $_POST[$field]), true);
					break;
				default: 
					$config[$field] = $_POST[$field];
			}
		}
	}
	
	$rewrite = '##GENERATED BY LANDO, DO NOT EDIT IN HERE##
<IfModule mod_rewrite.c>
	RewriteEngine On    																			# Turn on rewriting
	RewriteCond 	%{REQUEST_FILENAME} 	!-f 
	RewriteCond 	%{REQUEST_FILENAME} 	!-d 
	RewriteRule 	^(.*)$ 								index.php/$1 		[L] 	# If not a file, hide index.php
</IfModule>
##END LANDO GENERATED REWRITE##';

	$htaccess = "$doc_root/.htaccess";
	$apache = "";
	
	if(file_exists($htaccess))
		$apache = str_replace($rewrite, "", @file_get_contents($htaccess));

	if($config["pretty_urls"])
		$apache .= "\n\n".$rewrite;

	if(!$apache && file_exists($htaccess))
		unlink($htaccess);
	elseif(!@file_put_contents($htaccess, $apache))
		$error = "Error reading/writing <em>.htaccess</em> file. Please set its permissions to <strong>0777</strong>.";
	
	if(!@file_put_contents("$doc_root/app/config/config.php", "<?php\n\n".'$config = '.var_export($config, true).";"))
		$error = "Error saving config. Please set permissions on <em>app/config</em> and files within to <strong>0777</strong>.";
}

//redirect up to parent directory
$protocol = (isset($_SERVER["HTTPS"])) ? "https" : "http";
$host  = $_SERVER['HTTP_HOST'];
$uri   = rtrim(dirname($_SERVER['PHP_SELF']), '/\\');

$redirect = "Location: $protocol://$host$uri/";

if($error)
	$redirect .= "?error=".urlencode($error);
else
	$redirect .= "?saved=1";

header($redirect);
